In [1]:
import numpy as np
import pandas as pd

In [5]:
bee_df = pd.read_csv("data/bee_images/bee_data.csv")

In [7]:
bee_df.columns

Index(['file', 'date', 'time', 'location', 'zip code', 'subspecies', 'health',
       'pollen_carrying', 'caste'],
      dtype='object')

In [10]:
location = pd.read_csv('us-zip-code-latitude-and-longitude.csv', sep = ';')

In [11]:
location.head(2)

,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,55795,Willow River,MN,46.317812,-92.84315,-6,1,"46.317812,-92.84315"
1,45388,Yorkshire,OH,40.328535,-84.47938,-5,1,"40.328535,-84.47938"

In [12]:
location.columns

Index(['Zip', 'City', 'State', 'Latitude', 'Longitude', 'Timezone',
       'Daylight savings time flag', 'geopoint'],
      dtype='object')

In [18]:
bee_full = bee_df.merge(location, how = "left", left_on = 'zip code', right_on = 'Zip')

In [19]:
bee_full

,file,date,time,location,zip code,subspecies,health,pollen_carrying,caste,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,041_066.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
1,041_072.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
2,041_073.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
3,041_067.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
4,041_059.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,027_011.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,True,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5168,027_007.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,True,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5169,027_013.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5170,027_012.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5171,027_014.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"

In [24]:
bee_full = bee_full.drop_duplicates(subset='zip code', keep="first")
bee_full

,file,date,time,location,zip code,subspecies,health,pollen_carrying,caste,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,041_066.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
74,017_029.png,8/6/18,13:21,"Saratoga, CA, USA",95070,Italian honey bee,healthy,False,worker,95070,Saratoga,CA,37.270543,-122.02305,-8,1,"37.270543,-122.02305"
514,036_094.png,8/21/18,15:56,"Athens, GA, USA",30607,Italian honey bee,"few varrao, hive beetles",False,worker,30607,Athens,GA,34.013154,-83.43565,-5,1,"34.013154,-83.43565"
540,029_004.png,8/20/18,9:53,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
553,008_127.png,8/16/18,8:20,"New Orleans, LA, USA",70115,VSH Italian honey bee,healthy,False,worker,70115,New Orleans,LA,29.927305,-90.10197,-6,1,"29.927305,-90.10197"
1167,011_027.png,8/19/18,18:30,"Des Moines, IA, USA",50315,Carniolan honey bee,healthy,False,worker,50315,Des Moines,IA,41.545089,-93.61904,-6,1,"41.545089,-93.61904"
1943,002_024.png,8/25/18,14:00,"Keene, NH, USA",3431,Russian honey bee,healthy,False,worker,3431,Keene,NH,42.946418,-72.28616,-5,1,"42.946418,-72.28616"

In [26]:
urls = np.array("https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/001_043.png", 
        "https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/017_029.png",
        "https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/036_094.png",
        "https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/029_004.png",
        "https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/008_127.png",
        "https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/011_027.png",
        "https://github.com/JuliaWood1/DH151/blob/main/Week%204/data/bee_images/bee_imgs/bee_imgs/002_024.png"])



urls

ValueError: only 2 non-keyword arguments accepted

In [ ]:
bee_full['html_url']

In [25]:
bee_full.to_csv('bee_full.csv')

In [22]:
bee_full.iloc[0:999, :].to_csv('bee_full.csv')

In [23]:
bee_full.iloc[0:999, :]

,file,date,time,location,zip code,subspecies,health,pollen_carrying,caste,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,041_066.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
1,041_072.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
2,041_073.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
3,041_067.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
4,041_059.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,030_857.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
995,030_843.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
996,030_670.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
997,030_664.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
998,030_880.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"