In [1]:
import numpy as np
import pandas as pd

In [5]:
bee_df = pd.read_csv("data/bee_images/bee_data.csv")

In [7]:
bee_df.columns

Index(['file', 'date', 'time', 'location', 'zip code', 'subspecies', 'health',
       'pollen_carrying', 'caste'],
      dtype='object')

In [10]:
location = pd.read_csv('us-zip-code-latitude-and-longitude.csv', sep = ';')

In [11]:
location.head(2)

,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,55795,Willow River,MN,46.317812,-92.84315,-6,1,"46.317812,-92.84315"
1,45388,Yorkshire,OH,40.328535,-84.47938,-5,1,"40.328535,-84.47938"

In [12]:
location.columns

Index(['Zip', 'City', 'State', 'Latitude', 'Longitude', 'Timezone',
       'Daylight savings time flag', 'geopoint'],
      dtype='object')

In [18]:
bee_full = bee_df.merge(location, how = "left", left_on = 'zip code', right_on = 'Zip')

In [19]:
bee_full

,file,date,time,location,zip code,subspecies,health,pollen_carrying,caste,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,041_066.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
1,041_072.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
2,041_073.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
3,041_067.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
4,041_059.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.411480,-95.24475,-6,1,"29.41148,-95.24475"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,027_011.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,True,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5168,027_007.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,True,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5169,027_013.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5170,027_012.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"
5171,027_014.png,8/20/18,10:03,"San Jose, CA, USA",95124,-1,healthy,False,worker,95124,San Jose,CA,37.256743,-121.92312,-8,1,"37.256743,-121.92312"

In [22]:
bee_full.iloc[0:999, :].to_csv('bee_full.csv')

In [23]:
bee_full.iloc[0:999, :]

,file,date,time,location,zip code,subspecies,health,pollen_carrying,caste,Zip,City,State,Latitude,Longitude,Timezone,Daylight savings time flag,geopoint
0,041_066.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
1,041_072.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
2,041_073.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
3,041_067.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
4,041_059.png,8/28/18,16:07,"Alvin, TX, USA",77511,-1,hive being robbed,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,030_857.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
995,030_843.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
996,030_670.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
997,030_664.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"
998,030_880.png,8/17/18,17:50,"Alvin, TX, USA",77511,Italian honey bee,ant problems,False,worker,77511,Alvin,TX,29.41148,-95.24475,-6,1,"29.41148,-95.24475"